### ISSUE TITLE
ValueError: "concat" mode can only merge layers with matching output shapes except for the concat axis. Layer shapes: [(None, 1024, 14, 7), (None, 256, 14, 14)]

### ISSUE THREAD

**Issue by BooruguapalliSridhar** [ternaus/kaggle_dstl_submission#14]
I ran the **make_prediction_cropped_buildings.py** ,after below classes

1. python get_3_band_shapes.py
2. cache_train.py

got the ValueError.

**python make_prediction_cropped_buildings.py**
Using TensorFlow backend.
Traceback (most recent call last):
  File "make_prediction_cropped_buildings.py", line 26, in <module>
    model = read_model()
  File "make_prediction_cropped_buildings.py", line 21, in read_model
    model = model_from_json(open(os.path.join('../src/cache', json_name)).read())
  File "/home/darshan/anaconda2/lib/python2.7/site-packages/keras/models.py", line 214, in model_from_json
    return layer_from_config(config, custom_objects=custom_objects)
  File "/home/darshan/anaconda2/lib/python2.7/site-packages/keras/utils/layer_utils.py", line 44, in layer_from_config
    custom_objects=custom_objects)
  File "/home/darshan/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 2596, in from_config
    process_layer(layer_data)
  File "/home/darshan/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 2592, in process_layer
    layer(input_tensors)
  File "/home/darshan/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 1469, in __call__
    node_indices, tensor_indices)
  File "/home/darshan/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 1379, in _arguments_validation
    'Layer shapes: %s' % (input_shapes))
ValueError: "concat" mode can only merge layers with matching output shapes except for the concat axis. Layer shapes: [(None, 1024, 14, 7), (None, 256, 14, 14)]

Can any one help me on this?

Thanks

**Comment by BooruguapalliSridhar** [comment]
keras version 1.2.2, also tried with 1.2.1 and 1.2.0. and keras.json { "image_dim_ordering": "tf", "epsilon": 1e-07, "floatx": "float32", "backend": "tensorflow" } ,also added "image_data_format": "channels_first" to keras json file,still not working

**Comment by ternaus** [comment]
At the time when we worked on this problem, Theano was still supported and was working faster than Tensorflow.

Theano and Tensorflow have different dim_ordering. It may happen that using dim_ordering th will solve the problem.
