### ISSUE TITLE
 ValueError: "concat" mode can only merge layers with matching output shapes except for the concat axis. Layer shapes: [(None, 2, 14, 512), (None, 2, 14, 256)]

### ISSUE THREAD

**Issue by WenwenQi** [ternaus/kaggle_dstl_submission#3]
I run you code "unet_buildings.py" to train model. then I got an error as following: 

[2017-11-16 09:49:53.996358] Creating and compiling model...
Traceback (most recent call last):
  File "unet_buildings.py", line 254, in <module>
    model = get_unet0()
  File "unet_buildings.py", line 104, in get_unet0
    up6 = merge([UpSampling2D(size=(2, 2))(conv5), conv4], mode='concat', concat_axis=1)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1680, in merge
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1299, in __init__
    node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1371, in _arguments_validation
    'Layer shapes: %s' % (input_shapes))
ValueError: "concat" mode can only merge layers with matching output shapes except for the concat axis. Layer shapes: [(None, 2, 14, 512), (None, 2, 14, 256)]

I use keras+Theano+GPU. 
Any idea why it is crashing?

Many Thanks!

**Comment by WenwenQi** [comment]
plus: I use LINUX system.

**Comment by dmpetrov** [comment]
@WenwenQi, you can try to set `image_dim_ordering` to Theano `th` in `~/.keras/keras.json`.

**Comment by WenwenQi** [comment]
@dmpetrov  Thanks a lot. 
I resolved this problem by set "unet_buildings.py"  code : 
up6 = merge([UpSampling2D(size=(2, 2))(conv5), conv4], mode='concat', concat_axis=1)
change "concat_axis=1" to "concat_axis= -1" to match [2, 14, 512] and [2, 14, 256].

**Comment by cug-chenhui** [comment]
## I meet the same question as you. and I change "concat_axis=1" to "concat_axis= -1"  from up6 to up9, but I got an error as following:
File "/home/chen-h/PycharmProjects/3th kaggle_dstl_submission-master/kaggle_dstl_submission-master/src/unet_trees.py", line 250, in <module>
    model = get_unet0()
  File "/home/chen-h/PycharmProjects/3th kaggle_dstl_submission-master/kaggle_dstl_submission-master/src/unet_trees.py", line 133, in get_unet0
    conv9 = BatchNormalization(mode=0, axis=1)(crop9)
  File "/home/chen-h/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 575, in __call__
    self.build(input_shapes[0])
  File "/home/chen-h/anaconda3/lib/python3.6/site-packages/keras/layers/normalization.py", line 103, in build
    constraint=self.gamma_constraint)
  File "/home/chen-h/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/chen-h/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 396, in add_weight
    weight = K.variable(initializer(shape),
  File "/home/chen-h/anaconda3/lib/python3.6/site-packages/keras/initializers.py", line 41, in __call__
    return K.constant(1, shape=shape, dtype=dtype)
  File "/home/chen-h/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 358, in constant
    return tf.constant(value, dtype=dtype, shape=shape, name=name)
  File "/home/chen-h/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 99, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/chen-h/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 421, in make_tensor_proto
    (shape_size, nparray.size))
ValueError: Too many elements provided. Needed at most -16, but received 1

## It seems to caused by the following code:
    conv9 = Convolution2D(32, 3, 3, border_mode='same', init='he_uniform')(conv9)
    crop9 = Cropping2D(cropping=((16, 16), (16, 16)))(conv9)
    conv9 = BatchNormalization(mode=0, axis=1)(crop9)

Can you give me some advice?
thanks a lot.

**Comment by johnny-salz** [comment]
@cug-chenhui you have to carefully check where do you place your channels and correct channel_axis everywhere starting from your input, then check every layer to the output. Or use the same channel as was originally intended :)

**Comment by degiorgig** [comment]
@cepera-ang  do you mind being more specific? sorry I'm also facing this issue

**Comment by johnny-salz** [comment]
@leader80 there are two ways to organize image data: NCHW or channels_first and NHWC or channels_last. First N stands for N images in batch, C stands for channels and H, W is height and width of image. As you can see in the code, this network defaults to NCHW input (for example, look here https://github.com/ternaus/kaggle_dstl_submission/blob/master/src/unet_buildings.py#L63) and Theano backend used during training does the same too. It means that all convolutions change C axis of tensor (second place, index 1 starting from zero) and pooling layers change only H and W, thus concat_axis everywhere is 1, as we concat tensors of the same height and width and only different number of channels and batchnorm axis also 1 (along channels). 

New versions of Keras use Tensorflow backend and Tensorflow uses NHWC by default because it is faster on CPU (sic!) (see discussion [here](https://www.tensorflow.org/performance/performance_guide#data_formats)). So this change messes up all the axes in the network. There are to ways dealing with it: 
- first option, add old ordering option to Keras config file (lookup at google how to do it in current version), -
- second option, change input to be NHWC format and replace all concat and batch norm axes to -1. 

That's it, hope this helps
